@startuml uc2_2_add_calenda
:User: as actor
boundary "Announcement view" as view
boundary "add calendar view" as calendarView
control "calendar controller" as controller
entity database

'connections

actor --r-> view
view --r-> calendarView
calendarView --r-> controller
controller --r-> database
@enduml